name: Portfolio Deployment

on:
  push:
    branches:
      - main

jobs:
  build_prod:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Deploy using SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /home/front/portfolio/
            rm -rf frontend

            git clone --branch main https://${{ secrets.PAT }}@github.com/ablfaxl/portfolio.git frontend

            cd frontend
            docker compose up --build -d portfolio
